### 服务端口
server:
  port: 8089
### 服务名字
spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://localhost:8080
### 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/

