server:
  port: 8098
spring:
  application:
    name: service-consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: service-consul #注册在consul上面的名字，在consul的调用中，是通过此名字调用的
        register-health-check: true #健康检查，保证服务处于启动状态，建议开启