### 服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
### 服务端口
server:
  port: 8091
### 服务名称
spring:
  application:
    name: service-ribbon
  zipkin:
    base-url: http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-headers: "*"
        allowed-methods: "*"